// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: udp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UDP {

  /// <summary>Holder for reflection information generated from udp.proto</summary>
  public static partial class UdpReflection {

    #region Descriptor
    /// <summary>File descriptor for udp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UdpReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgl1ZHAucHJvdG8SA1VEUCI7CgpNc2dTZXNzaW9uEg8KB3Nlc3Npb24YASAB",
            "KAYSDQoFY2hlY2sYAiABKAcSDQoFaW5kZXgYAyABKA0iXgoLTXNnRGF0YUhl",
            "YWQSEwoLcGFja2V0X3R5cGUYASABKA0SFAoMY29uZmlybV90eXBlGAIgASgN",
            "EhEKCWFja19pbmRleBgDIAEoDRIRCgltc2dfaW5kZXgYBCABKA0qMgoNVWRw",
            "UGFja2V0VHlwZRIPCgtNU0dfQ09ORklUTRAAEhAKDE1TR19ORUVEX0FDSxAB",
            "KjAKDk1zZ0NvbmZpcm1UeXBlEgsKB01TR19BQ0sQABIRCg1NU0dfSEVBUlRC",
            "RUFUEAEqMgoMVWRwRXJyb3JUeXBlEhAKDElOVkFMSURfVFlQRRAAEhAKDE5F",
            "RURfUkVMT0dJThABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::UDP.UdpPacketType), typeof(global::UDP.MsgConfirmType), typeof(global::UDP.UdpErrorType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UDP.MsgSession), global::UDP.MsgSession.Parser, new[]{ "Session", "Check", "Index" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UDP.MsgDataHead), global::UDP.MsgDataHead.Parser, new[]{ "PacketType", "ConfirmType", "AckIndex", "MsgIndex" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum UdpPacketType {
    /// <summary>
    /// ACK or Heartbeat. 【ACK或心跳包】
    /// </summary>
    [pbr::OriginalName("MSG_CONFITM")] MsgConfitm = 0,
    /// <summary>
    /// Packet with request, and need server ACK. 【需要服务器ACK的数据包】
    /// </summary>
    [pbr::OriginalName("MSG_NEED_ACK")] MsgNeedAck = 1,
  }

  public enum MsgConfirmType {
    /// <summary>
    /// ACK for other end.【发往另一端的ACK】
    /// </summary>
    [pbr::OriginalName("MSG_ACK")] MsgAck = 0,
    /// <summary>
    /// Heartbeat packet.【发往另一端的心跳包】
    /// </summary>
    [pbr::OriginalName("MSG_HEARTBEAT")] MsgHeartbeat = 1,
  }

  public enum UdpErrorType {
    [pbr::OriginalName("INVALID_TYPE")] InvalidType = 0,
    [pbr::OriginalName("NEED_RELOGIN")] NeedRelogin = 1,
  }

  #endregion

  #region Messages
  public sealed partial class MsgSession : pb::IMessage<MsgSession>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgSession> _parser = new pb::MessageParser<MsgSession>(() => new MsgSession());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgSession> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UDP.UdpReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgSession() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgSession(MsgSession other) : this() {
      session_ = other.session_;
      check_ = other.check_;
      index_ = other.index_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgSession Clone() {
      return new MsgSession(this);
    }

    /// <summary>Field number for the "session" field.</summary>
    public const int SessionFieldNumber = 1;
    private ulong session_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Session {
      get { return session_; }
      set {
        session_ = value;
      }
    }

    /// <summary>Field number for the "check" field.</summary>
    public const int CheckFieldNumber = 2;
    private uint check_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Check {
      get { return check_; }
      set {
        check_ = value;
      }
    }

    /// <summary>Field number for the "index" field.</summary>
    public const int IndexFieldNumber = 3;
    private uint index_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgSession);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgSession other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Session != other.Session) return false;
      if (Check != other.Check) return false;
      if (Index != other.Index) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Session != 0UL) hash ^= Session.GetHashCode();
      if (Check != 0) hash ^= Check.GetHashCode();
      if (Index != 0) hash ^= Index.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Session != 0UL) {
        output.WriteRawTag(9);
        output.WriteFixed64(Session);
      }
      if (Check != 0) {
        output.WriteRawTag(21);
        output.WriteFixed32(Check);
      }
      if (Index != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Index);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Session != 0UL) {
        output.WriteRawTag(9);
        output.WriteFixed64(Session);
      }
      if (Check != 0) {
        output.WriteRawTag(21);
        output.WriteFixed32(Check);
      }
      if (Index != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Index);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Session != 0UL) {
        size += 1 + 8;
      }
      if (Check != 0) {
        size += 1 + 4;
      }
      if (Index != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Index);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgSession other) {
      if (other == null) {
        return;
      }
      if (other.Session != 0UL) {
        Session = other.Session;
      }
      if (other.Check != 0) {
        Check = other.Check;
      }
      if (other.Index != 0) {
        Index = other.Index;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Session = input.ReadFixed64();
            break;
          }
          case 21: {
            Check = input.ReadFixed32();
            break;
          }
          case 24: {
            Index = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Session = input.ReadFixed64();
            break;
          }
          case 21: {
            Check = input.ReadFixed32();
            break;
          }
          case 24: {
            Index = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MsgDataHead : pb::IMessage<MsgDataHead>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgDataHead> _parser = new pb::MessageParser<MsgDataHead>(() => new MsgDataHead());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgDataHead> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UDP.UdpReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgDataHead() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgDataHead(MsgDataHead other) : this() {
      packetType_ = other.packetType_;
      confirmType_ = other.confirmType_;
      ackIndex_ = other.ackIndex_;
      msgIndex_ = other.msgIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgDataHead Clone() {
      return new MsgDataHead(this);
    }

    /// <summary>Field number for the "packet_type" field.</summary>
    public const int PacketTypeFieldNumber = 1;
    private uint packetType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PacketType {
      get { return packetType_; }
      set {
        packetType_ = value;
      }
    }

    /// <summary>Field number for the "confirm_type" field.</summary>
    public const int ConfirmTypeFieldNumber = 2;
    private uint confirmType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ConfirmType {
      get { return confirmType_; }
      set {
        confirmType_ = value;
      }
    }

    /// <summary>Field number for the "ack_index" field.</summary>
    public const int AckIndexFieldNumber = 3;
    private uint ackIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AckIndex {
      get { return ackIndex_; }
      set {
        ackIndex_ = value;
      }
    }

    /// <summary>Field number for the "msg_index" field.</summary>
    public const int MsgIndexFieldNumber = 4;
    private uint msgIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MsgIndex {
      get { return msgIndex_; }
      set {
        msgIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgDataHead);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgDataHead other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PacketType != other.PacketType) return false;
      if (ConfirmType != other.ConfirmType) return false;
      if (AckIndex != other.AckIndex) return false;
      if (MsgIndex != other.MsgIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PacketType != 0) hash ^= PacketType.GetHashCode();
      if (ConfirmType != 0) hash ^= ConfirmType.GetHashCode();
      if (AckIndex != 0) hash ^= AckIndex.GetHashCode();
      if (MsgIndex != 0) hash ^= MsgIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PacketType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PacketType);
      }
      if (ConfirmType != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ConfirmType);
      }
      if (AckIndex != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(AckIndex);
      }
      if (MsgIndex != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(MsgIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PacketType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PacketType);
      }
      if (ConfirmType != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ConfirmType);
      }
      if (AckIndex != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(AckIndex);
      }
      if (MsgIndex != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(MsgIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PacketType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PacketType);
      }
      if (ConfirmType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ConfirmType);
      }
      if (AckIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AckIndex);
      }
      if (MsgIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MsgIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgDataHead other) {
      if (other == null) {
        return;
      }
      if (other.PacketType != 0) {
        PacketType = other.PacketType;
      }
      if (other.ConfirmType != 0) {
        ConfirmType = other.ConfirmType;
      }
      if (other.AckIndex != 0) {
        AckIndex = other.AckIndex;
      }
      if (other.MsgIndex != 0) {
        MsgIndex = other.MsgIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PacketType = input.ReadUInt32();
            break;
          }
          case 16: {
            ConfirmType = input.ReadUInt32();
            break;
          }
          case 24: {
            AckIndex = input.ReadUInt32();
            break;
          }
          case 32: {
            MsgIndex = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PacketType = input.ReadUInt32();
            break;
          }
          case 16: {
            ConfirmType = input.ReadUInt32();
            break;
          }
          case 24: {
            AckIndex = input.ReadUInt32();
            break;
          }
          case 32: {
            MsgIndex = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
